version: "3.7"
services:
  api:
    build:
      args:
        - TRAVIS_BRANCH
    ports:
      - "8080:8080"
    environment:
      PUBLIC_URL: http://api:8080
      OPERATIONS_SECRET: API-tests
      HEALTH_CHECK_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6ImV4ZWN1dGU6aGVhbHRoLWNoZWNrIn0.FQgIMpaHZX_7yPWRNC5HAsmlYWkNYu0pdNrSil3ECRc
      APPLICATION_CONTROL_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6ImV4ZWN1dGU6YXBwbGljYXRpb24tY29udHJvbCJ9.CCMnq-6mlX-ZoSC2OfwdBOVn5DILmahP58hfXowjqFk
      CONSUL_AGENT_LOCATION: http://consul:8500
    depends_on:
      - consul
  consul:
    image: consul:1.6
    ports:
      - "8500:8500"
    environment:
      CONSUL_LOCAL_CONFIG: {"enable_script_checks":true}
