version: '3'
services:
  api:
    build:
      context: ../../
      dockerfile: docker/pharo/Dockerfile
    ports:
      - "8080:8080"
    environment:
      STARGATE__PUBLIC_URL: http://api:8080
      STARGATE__PORT: 8080
      STARGATE__OPERATIONS_SECRET: API-tests
      HEALTH_CHECK_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJleGVjdXRlOmhlYWx0aC1jaGVjayJdfQ.gLammIebJuNDYDz70T8ZYK9GV8jXWrt18mPnLPvoCjw
      STARGATE__CONSUL_AGENT_LOCATION: http://consul-agent:8500
    depends_on:
      - consul-agent
  consul-agent:
    image: consul:1.8
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8300:8300"
    environment:
      CONSUL_BIND_INTERFACE: eth0
