name: Build and Publish Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Build and Publish Docker Images
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository_owner }}/stargate-consul-example
      - name: Set branch name
        id: set-branch-name
        run: |
          if [[ -z "${GITHUB_HEAD_REF##*/}" ]]; then
            echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"
          else
            echo "::set-output name=BRANCH_NAME::${GITHUB_HEAD_REF##*/}"
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v2
        env:
          BRANCH_NAME: ${{ steps.set-branch-name.outputs.BRANCH_NAME }}
        with:
          context: ./docker
          file: ./docker/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          secrets: |
              GIT_AUTH_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
